services:
  so100_ros2_dev:
    build:
      context: ..
      target: base
      args:
        ROS_DISTRO: humble
    container_name: so100_ros2_devcontainer

    # === Tune this to your application ===
    network_mode: "host"
    ipc: "host"
    pid: "host"
    privileged: true
    # ===

    command: /bin/bash
    tty: true
    stdin_open: true

    volumes:
      - $HOME/.Xauthority:/root/.Xauthority 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - /dev:/dev

    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 100
      RCUTILS_COLORIZED_OUTPUT: 1
      SHELL: /bin/bash

    cap_add:
      - SYS_NICE

    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856

